apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: demo-api
  name: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-api
  template:
    metadata:
      labels:
        run: demo-api
    spec:
      containers:
      - image: controlplane/demo-api:29-b2890691ec9dd74bfcd9f34b520b9d5b0a1d6aac
        imagePullPolicy: Always
        name: demo-api
        ports:
        - containerPort: 9000
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
